# Generated by Django 3.1 on 2020-09-18 20:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200915_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('contatos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=350)),
                ('data', models.DateField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=8)),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_joined',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 18, 17, 17, 57, 194183)),
        ),
        migrations.CreateModel(
            name='Reacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
                ('data', models.DateField(auto_now_add=True)),
                ('peso', models.CharField(max_length=35)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.perfil')),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.postagem')),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usuario'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=150)),
                ('data', models.DateField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.perfil')),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.postagem')),
            ],
        ),
    ]
