# Generated by Django 3.1 on 2020-09-18 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200918_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_joined',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 18, 17, 37, 16, 204367)),
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='contatos',
        ),
        migrations.AddField(
            model_name='perfil',
            name='contatos',
            field=models.ManyToManyField(related_name='_perfil_contatos_+', to='myapp.Perfil'),
        ),
    ]
