# Generated by Django 3.1 on 2020-09-18 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20200918_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_joined',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 18, 17, 59, 33, 330352)),
        ),
    ]
